// WARNING: Please don't edit this file. It was generated by Swift/WinRT v0.0.1
// swiftlint:disable all
import Foundation
@_spi(WinRTInternal) @_spi(WinRTImplements) import WindowsFoundation
import CWinRT

/// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.system.userauthenticationstatus)
public typealias UserAuthenticationStatus = __x_ABI_CWindows_CSystem_CUserAuthenticationStatus
/// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.system.userpicturesize)
public typealias UserPictureSize = __x_ABI_CWindows_CSystem_CUserPictureSize
/// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.system.usertype)
public typealias UserType = __x_ABI_CWindows_CSystem_CUserType
/// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.system.userwatcherstatus)
public typealias UserWatcherStatus = __x_ABI_CWindows_CSystem_CUserWatcherStatus
/// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.system.user)
public final class User : WinRTClass {
    private typealias SwiftABI = __ABI_Windows_System.IUser
    private typealias CABI = __x_ABI_CWindows_CSystem_CIUser
    private lazy var _default: SwiftABI! = getInterfaceForCaching()
    @_spi(WinRTInternal)
    override public func _getABI<T>() -> UnsafeMutablePointer<T>? {
        if T.self == CABI.self {
            return RawPointer(_default)
        }
        return super._getABI()
    }

    @_spi(WinRTInternal)
    public init(fromAbi: WindowsFoundation.IInspectable) {
        super.init(fromAbi)
    }

    private static let _IUserStatics: __ABI_Windows_System.IUserStatics = try! RoGetActivationFactory("Windows.System.User")
    /// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.system.user.createwatcher)
    public static func createWatcher() throws -> UserWatcher! {
        return try _IUserStatics.CreateWatcher()
    }

    /// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.system.user.findallasync)
    public static func findAllAsync() throws -> WindowsFoundation.AnyIAsyncOperation<WindowsFoundation.AnyIVectorView<User?>?>! {
        return try _IUserStatics.FindAllAsync()
    }

    /// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.system.user.findallasync)
    public static func findAllAsync(_ type: UserType) throws -> WindowsFoundation.AnyIAsyncOperation<WindowsFoundation.AnyIVectorView<User?>?>! {
        return try _IUserStatics.FindAllAsyncByType(type)
    }

    /// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.system.user.findallasync)
    public static func findAllAsync(_ type: UserType, _ status: UserAuthenticationStatus) throws -> WindowsFoundation.AnyIAsyncOperation<WindowsFoundation.AnyIVectorView<User?>?>! {
        return try _IUserStatics.FindAllAsyncByTypeAndStatus(type, status)
    }

    /// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.system.user.getfromid)
    public static func getFromId(_ nonRoamableId: String) throws -> User! {
        return try _IUserStatics.GetFromId(nonRoamableId)
    }

    /// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.system.user.getpropertyasync)
    public func getPropertyAsync(_ value: String) throws -> WindowsFoundation.AnyIAsyncOperation<Any?>! {
        try _default.GetPropertyAsync(value)
    }

    /// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.system.user.getpropertiesasync)
    public func getPropertiesAsync(_ values: WindowsFoundation.AnyIVectorView<String>!) throws -> WindowsFoundation.AnyIAsyncOperation<WindowsFoundation.AnyIPropertySet?>! {
        try _default.GetPropertiesAsync(values)
    }

    /// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.system.user.getpictureasync)
    public func getPictureAsync(_ desiredSize: UserPictureSize) throws -> WindowsFoundation.AnyIAsyncOperation<UWP.AnyIRandomAccessStreamReference?>! {
        try _default.GetPictureAsync(desiredSize)
    }

    /// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.system.user.authenticationstatus)
    public var authenticationStatus : UserAuthenticationStatus {
        get { try! _default.get_AuthenticationStatus() }
    }

    /// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.system.user.nonroamableid)
    public var nonRoamableId : String {
        get { try! _default.get_NonRoamableId() }
    }

    /// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.system.user.type)
    public var type : UserType {
        get { try! _default.get_Type() }
    }

    deinit {
        _default = nil
    }
}

/// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.system.userauthenticationstatuschangedeferral)
public final class UserAuthenticationStatusChangeDeferral : WinRTClass {
    private typealias SwiftABI = __ABI_Windows_System.IUserAuthenticationStatusChangeDeferral
    private typealias CABI = __x_ABI_CWindows_CSystem_CIUserAuthenticationStatusChangeDeferral
    private lazy var _default: SwiftABI! = getInterfaceForCaching()
    @_spi(WinRTInternal)
    override public func _getABI<T>() -> UnsafeMutablePointer<T>? {
        if T.self == CABI.self {
            return RawPointer(_default)
        }
        return super._getABI()
    }

    @_spi(WinRTInternal)
    public init(fromAbi: WindowsFoundation.IInspectable) {
        super.init(fromAbi)
    }

    /// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.system.userauthenticationstatuschangedeferral.complete)
    public func complete() throws {
        try _default.Complete()
    }

    deinit {
        _default = nil
    }
}

/// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.system.userauthenticationstatuschangingeventargs)
public final class UserAuthenticationStatusChangingEventArgs : WinRTClass {
    private typealias SwiftABI = __ABI_Windows_System.IUserAuthenticationStatusChangingEventArgs
    private typealias CABI = __x_ABI_CWindows_CSystem_CIUserAuthenticationStatusChangingEventArgs
    private lazy var _default: SwiftABI! = getInterfaceForCaching()
    @_spi(WinRTInternal)
    override public func _getABI<T>() -> UnsafeMutablePointer<T>? {
        if T.self == CABI.self {
            return RawPointer(_default)
        }
        return super._getABI()
    }

    @_spi(WinRTInternal)
    public init(fromAbi: WindowsFoundation.IInspectable) {
        super.init(fromAbi)
    }

    /// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.system.userauthenticationstatuschangingeventargs.getdeferral)
    public func getDeferral() throws -> UserAuthenticationStatusChangeDeferral! {
        try _default.GetDeferral()
    }

    /// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.system.userauthenticationstatuschangingeventargs.currentstatus)
    public var currentStatus : UserAuthenticationStatus {
        get { try! _default.get_CurrentStatus() }
    }

    /// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.system.userauthenticationstatuschangingeventargs.newstatus)
    public var newStatus : UserAuthenticationStatus {
        get { try! _default.get_NewStatus() }
    }

    /// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.system.userauthenticationstatuschangingeventargs.user)
    public var user : User! {
        get { try! _default.get_User() }
    }

    deinit {
        _default = nil
    }
}

/// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.system.userchangedeventargs)
public final class UserChangedEventArgs : WinRTClass {
    private typealias SwiftABI = __ABI_Windows_System.IUserChangedEventArgs
    private typealias CABI = __x_ABI_CWindows_CSystem_CIUserChangedEventArgs
    private lazy var _default: SwiftABI! = getInterfaceForCaching()
    @_spi(WinRTInternal)
    override public func _getABI<T>() -> UnsafeMutablePointer<T>? {
        if T.self == CABI.self {
            return RawPointer(_default)
        }
        return super._getABI()
    }

    @_spi(WinRTInternal)
    public init(fromAbi: WindowsFoundation.IInspectable) {
        super.init(fromAbi)
    }

    /// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.system.userchangedeventargs.user)
    public var user : User! {
        get { try! _default.get_User() }
    }

    deinit {
        _default = nil
    }
}

/// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.system.userwatcher)
public final class UserWatcher : WinRTClass {
    private typealias SwiftABI = __ABI_Windows_System.IUserWatcher
    private typealias CABI = __x_ABI_CWindows_CSystem_CIUserWatcher
    private lazy var _default: SwiftABI! = getInterfaceForCaching()
    @_spi(WinRTInternal)
    override public func _getABI<T>() -> UnsafeMutablePointer<T>? {
        if T.self == CABI.self {
            return RawPointer(_default)
        }
        return super._getABI()
    }

    @_spi(WinRTInternal)
    public init(fromAbi: WindowsFoundation.IInspectable) {
        super.init(fromAbi)
    }

    /// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.system.userwatcher.start)
    public func start() throws {
        try _default.Start()
    }

    /// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.system.userwatcher.stop)
    public func stop() throws {
        try _default.Stop()
    }

    /// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.system.userwatcher.status)
    public var status : UserWatcherStatus {
        get { try! _default.get_Status() }
    }

    /// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.system.userwatcher.added)
    public lazy var added : Event<TypedEventHandler<UserWatcher?, UserChangedEventArgs?>> = {
      .init(
        add: { [weak self] in
          guard let this = self?._default else { return .init() }
          return try! this.add_Added($0)
        },
        remove: { [weak self] in
         try? self?._default.remove_Added($0)
       }
      )
    }()

    /// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.system.userwatcher.authenticationstatuschanged)
    public lazy var authenticationStatusChanged : Event<TypedEventHandler<UserWatcher?, UserChangedEventArgs?>> = {
      .init(
        add: { [weak self] in
          guard let this = self?._default else { return .init() }
          return try! this.add_AuthenticationStatusChanged($0)
        },
        remove: { [weak self] in
         try? self?._default.remove_AuthenticationStatusChanged($0)
       }
      )
    }()

    /// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.system.userwatcher.authenticationstatuschanging)
    public lazy var authenticationStatusChanging : Event<TypedEventHandler<UserWatcher?, UserAuthenticationStatusChangingEventArgs?>> = {
      .init(
        add: { [weak self] in
          guard let this = self?._default else { return .init() }
          return try! this.add_AuthenticationStatusChanging($0)
        },
        remove: { [weak self] in
         try? self?._default.remove_AuthenticationStatusChanging($0)
       }
      )
    }()

    /// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.system.userwatcher.enumerationcompleted)
    public lazy var enumerationCompleted : Event<TypedEventHandler<UserWatcher?, Any?>> = {
      .init(
        add: { [weak self] in
          guard let this = self?._default else { return .init() }
          return try! this.add_EnumerationCompleted($0)
        },
        remove: { [weak self] in
         try? self?._default.remove_EnumerationCompleted($0)
       }
      )
    }()

    /// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.system.userwatcher.removed)
    public lazy var removed : Event<TypedEventHandler<UserWatcher?, UserChangedEventArgs?>> = {
      .init(
        add: { [weak self] in
          guard let this = self?._default else { return .init() }
          return try! this.add_Removed($0)
        },
        remove: { [weak self] in
         try? self?._default.remove_Removed($0)
       }
      )
    }()

    /// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.system.userwatcher.stopped)
    public lazy var stopped : Event<TypedEventHandler<UserWatcher?, Any?>> = {
      .init(
        add: { [weak self] in
          guard let this = self?._default else { return .init() }
          return try! this.add_Stopped($0)
        },
        remove: { [weak self] in
         try? self?._default.remove_Stopped($0)
       }
      )
    }()

    /// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.system.userwatcher.updated)
    public lazy var updated : Event<TypedEventHandler<UserWatcher?, UserChangedEventArgs?>> = {
      .init(
        add: { [weak self] in
          guard let this = self?._default else { return .init() }
          return try! this.add_Updated($0)
        },
        remove: { [weak self] in
         try? self?._default.remove_Updated($0)
       }
      )
    }()

    deinit {
        _default = nil
    }
}

extension UWP.UserAuthenticationStatus {
    public static var unauthenticated : UWP.UserAuthenticationStatus {
        __x_ABI_CWindows_CSystem_CUserAuthenticationStatus_Unauthenticated
    }
    public static var locallyAuthenticated : UWP.UserAuthenticationStatus {
        __x_ABI_CWindows_CSystem_CUserAuthenticationStatus_LocallyAuthenticated
    }
    public static var remotelyAuthenticated : UWP.UserAuthenticationStatus {
        __x_ABI_CWindows_CSystem_CUserAuthenticationStatus_RemotelyAuthenticated
    }
}
extension UWP.UserAuthenticationStatus: @retroactive Hashable, @retroactive Codable, @retroactive @unchecked Sendable {}

extension UWP.UserPictureSize {
    public static var size64x64 : UWP.UserPictureSize {
        __x_ABI_CWindows_CSystem_CUserPictureSize_Size64x64
    }
    public static var size208x208 : UWP.UserPictureSize {
        __x_ABI_CWindows_CSystem_CUserPictureSize_Size208x208
    }
    public static var size424x424 : UWP.UserPictureSize {
        __x_ABI_CWindows_CSystem_CUserPictureSize_Size424x424
    }
    public static var size1080x1080 : UWP.UserPictureSize {
        __x_ABI_CWindows_CSystem_CUserPictureSize_Size1080x1080
    }
}
extension UWP.UserPictureSize: @retroactive Hashable, @retroactive Codable, @retroactive @unchecked Sendable {}

extension UWP.UserType {
    public static var localUser : UWP.UserType {
        __x_ABI_CWindows_CSystem_CUserType_LocalUser
    }
    public static var remoteUser : UWP.UserType {
        __x_ABI_CWindows_CSystem_CUserType_RemoteUser
    }
    public static var localGuest : UWP.UserType {
        __x_ABI_CWindows_CSystem_CUserType_LocalGuest
    }
    public static var remoteGuest : UWP.UserType {
        __x_ABI_CWindows_CSystem_CUserType_RemoteGuest
    }
}
extension UWP.UserType: @retroactive Hashable, @retroactive Codable, @retroactive @unchecked Sendable {}

extension UWP.UserWatcherStatus {
    public static var created : UWP.UserWatcherStatus {
        __x_ABI_CWindows_CSystem_CUserWatcherStatus_Created
    }
    public static var started : UWP.UserWatcherStatus {
        __x_ABI_CWindows_CSystem_CUserWatcherStatus_Started
    }
    public static var enumerationCompleted : UWP.UserWatcherStatus {
        __x_ABI_CWindows_CSystem_CUserWatcherStatus_EnumerationCompleted
    }
    public static var stopping : UWP.UserWatcherStatus {
        __x_ABI_CWindows_CSystem_CUserWatcherStatus_Stopping
    }
    public static var stopped : UWP.UserWatcherStatus {
        __x_ABI_CWindows_CSystem_CUserWatcherStatus_Stopped
    }
    public static var aborted : UWP.UserWatcherStatus {
        __x_ABI_CWindows_CSystem_CUserWatcherStatus_Aborted
    }
}
extension UWP.UserWatcherStatus: @retroactive Hashable, @retroactive Codable, @retroactive @unchecked Sendable {}

