// WARNING: Please don't edit this file. It was generated by Swift/WinRT v0.0.1
// swiftlint:disable all
import Foundation
@_spi(WinRTInternal) @_spi(WinRTImplements) import WindowsFoundation
import CWinRT

/// [Open Microsoft documentation](https://learn.microsoft.com/uwp/api/windows.storage.provider.fileupdatestatus)
public typealias FileUpdateStatus = __x_ABI_CWindows_CStorage_CProvider_CFileUpdateStatus
extension UWP.FileUpdateStatus {
    public static var incomplete : UWP.FileUpdateStatus {
        __x_ABI_CWindows_CStorage_CProvider_CFileUpdateStatus_Incomplete
    }
    public static var complete : UWP.FileUpdateStatus {
        __x_ABI_CWindows_CStorage_CProvider_CFileUpdateStatus_Complete
    }
    public static var userInputNeeded : UWP.FileUpdateStatus {
        __x_ABI_CWindows_CStorage_CProvider_CFileUpdateStatus_UserInputNeeded
    }
    public static var currentlyUnavailable : UWP.FileUpdateStatus {
        __x_ABI_CWindows_CStorage_CProvider_CFileUpdateStatus_CurrentlyUnavailable
    }
    public static var failed : UWP.FileUpdateStatus {
        __x_ABI_CWindows_CStorage_CProvider_CFileUpdateStatus_Failed
    }
    public static var completeAndRenamed : UWP.FileUpdateStatus {
        __x_ABI_CWindows_CStorage_CProvider_CFileUpdateStatus_CompleteAndRenamed
    }
}
extension UWP.FileUpdateStatus: @retroactive Hashable, @retroactive Codable, @retroactive @unchecked Sendable {}

