name: Generate Swift Bindings

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Swift
        uses: compnerd/gha-setup-swift@main
        with:
          swift-version: swift-6.3-release
          swift-build: 6.3-RELEASE

      - name: Generate Bindings
        shell: pwsh
        run: swiftc -v generateBindings.swift
        
      - name: Swift Build
        shell: pwsh
        run: swift build

      - name: Commit
        uses: EndBug/add-and-commit@v10
