name: Generate Swift Bindings

# Schedule once a month

jobs:
  generate:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: ctions/checkout@v4

      - name: Generate Bindings
        shell: pwsh
        run ./generate-bindings.ps1

      - name: Commit
        uses: EndBug/add-and-commit@v10
